/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fproject.window;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jack
 */
public class Window extends javax.swing.JFrame {
    private final static String[] columnHeaders = {" ", "Website", "Username", "Password"};
    private DefaultTableModel accountsTableModel;
    private ArrayList<Account> accounts;
    private CompanyAPI api;
    
    /**
     * Creates new form Window
     */
    
    private static DefaultTableModel getNewDTM(){
        return new DefaultTableModel(null, columnHeaders){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
            @Override
            public Class getColumnClass(int columnIndex){
                return (columnIndex == 0)? ImageIcon.class: super.getColumnClass(columnIndex);
            }
        };
    }
    public Window() {     
        api = new CompanyAPI();
        accountsTableModel = getNewDTM();
        accounts = new ArrayList<>();
        initComponents();
        loadAccounts();
    }
    
    private void update(){
        accountsTableModel = getNewDTM();
        for(Account a:accounts){
            accountsTableModel.addRow(a.getRow());
        }
        accTable.setModel(accountsTableModel);
    }
    
    public void saveAccounts(){
        try{
            FileOutputStream fout = new FileOutputStream("accounts.dat");
            ObjectOutputStream aout = new ObjectOutputStream(fout);
            for(Account a: accounts){
                aout.writeObject(a);
            }
        }
        catch(FileNotFoundException e){
            
        } catch (IOException ex) {
            Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void loadAccounts(){
        try{
            FileInputStream fin = new FileInputStream("accounts.dat");
            ObjectInputStream ain = new ObjectInputStream(fin);
            Account a;
            while((a = (Account) ain.readObject()) != null){
                accounts.add(a);
            }
            
        }
        catch(FileNotFoundException e){
            
        } catch (IOException ex) {
            
        } catch (ClassNotFoundException ex) {
            
        } finally {
            update();
        }
    }
    
    public void returnFromSearch(Company company){
        if(company != null){
            String newUName = JOptionPane.showInputDialog(null, "Enter New Username", "Question: 1/2", JOptionPane.QUESTION_MESSAGE);
            String newPWord = JOptionPane.showInputDialog(null, "Enter New Password", "Question: 2/2", JOptionPane.QUESTION_MESSAGE);
            Account a = new Account(newUName, newPWord, company);
            accounts.add(a);
            update();
        }
        this.setEnabled(true);
    }   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEdit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        accTable = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnVisit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEdit.setText("Edit Account");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        accTable.setModel(accountsTableModel);
        jScrollPane2.setViewportView(accTable);

        btnAdd.setText("Add Account");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete Account");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnVisit.setText("Visit Site");
        btnVisit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVisit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnAdd)
                    .addComponent(btnDelete)
                    .addComponent(btnSave)
                    .addComponent(btnVisit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        int i = accTable.getSelectedRow();
        if(i < 0 || i >= accounts.size()){
            return;
        }
        //String webName = (String) accountsTableModel.getValueAt(i, 0);
        String newUName = JOptionPane.showInputDialog(null, "Enter New Username", "Question: 1/2", JOptionPane.QUESTION_MESSAGE);
        String newPWord = JOptionPane.showInputDialog(null, "Enter New Password", "Question: 2/2", JOptionPane.QUESTION_MESSAGE);
        Account a = accounts.get(i);
        a.setUsername(newUName);
        a.setPassword(newPWord);
        update();     
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        new CompanySearchFrame(this).setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int i = accTable.getSelectedRow();
        if(i < 0 || i >= accounts.size()){
            return;
        }
        accounts.remove(i);
        accountsTableModel.removeRow(i);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        saveAccounts();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnVisitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisitActionPerformed
        int i = accTable.getSelectedRow();
        if(i < 0 || i >= accounts.size()){
            return;
        }
        accounts.get(i).getCompany().navigate();
    }//GEN-LAST:event_btnVisitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable accTable;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnVisit;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
